# Generated by Django 6.0.8 on 2026-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Description Text', max_length=200),
            preserve_default=False,
        ),
    ]
